name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1
    - name: Init Submodules 
      run:  git submodule init && git submodule update --recursive   && git submodule sync
    - name: Build
      run: ./build.sh
 
